### ISSUE TITLE
Should use https: for API requests

### ISSUE THREAD

**Issue by gleneivey** [raul/pt#15]
By default, Tracker projects have "Use HTTPS--Require that API accesses for this project use SSL. Improves security of data, at the expense of some performance." turned on, which causes project-specific requests to fail with "400 Bad Request" unless they use https.  In my initial use of "pt" to do setup, it failed with this error on the get projects//memberships request after I selected my project.  Turning that setting of (not my preference) allowed me to proceed.

**Comment by drselump14** [comment]
The newest code use https for API request

I'll close this issue
