### ISSUE TITLE
Need to quote argument to mywork: filter

### ISSUE THREAD

**Issue by gleneivey** [raul/pt#16]
I happen to have my middle initial (followed by a period) in my name in Tracker.  This breaks the "my work" search that pt-without-arguments does.  You can fix it by wrapping the user's name with (URL escaped) single or double quotes.

**Comment by drselump14** [comment]
I know it's an old issue.. but does it still happen in the newest version?

I'll close this issue, please comment if the issue still exist ..

Thanks
