### ISSUE TITLE
case-insensitive email

### ISSUE THREAD

**Issue by soycamo** [raul/pt#27]
Pivotal Tracker is actually case-sensitive with regards to email, so if your registered email address is not the same case as what you entered in the prompt, you get this:

```
/path/pt-0.5.4/lib/pt/ui.rb:451:in `load_local_config': undefined method `name' for nil:NilClass (NoMethodError)
from /path/pt-0.5.4/lib/pt/ui.rb:15:in `initialize'
from /path/pt-0.5.4/bin/pt:8:in `new'
from /path/pt-0.5.4/bin/pt:8:in `<top (required)>'
from /path/bin/pt:19:in `load'
from /path/bin/pt:19:in `<main>'
```

**Comment by drselump14** [comment]
in the newest version, pt will only ask the the API token .. so the email address and password is not required anymore .
