### ISSUE TITLE
Unable to log in 

### ISSUE THREAD

**Issue by zeke** [raul/pt#60]
I know I'm using the right email and password. I can login in the browser without issue.

```
❯ pt --debug

I can't find info about your Pivotal Tracker account in /Users/z/.pt.
What is your email?
zeke@sikelianos.com
And your password? (won't be displayed on screen)
**************

Request: POST https://www.pivotaltracker.com/services/v3/tokens/active

Payload: username=zeke%40sikelianos.com&password=**************&timeout=60

Bad email/password combination. Please try again.
What is your email?
```

**Comment by orta** [comment]
They might have changed the API, I'm afraid I've not been using this for a few years now, so it might be worth taking a look around yourself.

**Comment by talsafran** [comment]
Hm worked for me just now?

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/v2m0z36v.png)

**Comment by talsafran** [comment]
@zeke you installed through bundler I'm assuming? If you're using rvm make sure it's installed in the gemset you're currently using.

**Comment by zeke** [comment]
Yeah it was some `rvm` nonsense. Thanks, @talsafran!
