### ISSUE TITLE
New gem forked from this repository, works with API v5

### ISSUE THREAD

**Issue by drselump14** [raul/pt#62]
Hello guys, it looks like this project is deprecated and unmaintained. So I decided to fork the project and upload a new gem called ptt that works with API v5. Enjoy :)

https://github.com/drselump14/ptt

https://rubygems.org/gems/ptt

**Comment by raul** [comment]
Very cool @drselump14 ! What do you think @orta? Should we add a notice to the README and repo description? Perhaps @drselump14 would be interested on maintaining `pt` rather than a fork?

**Comment by drselump14** [comment]
@raul sure, i'd  be happy to maintain this repository

**Comment by raul** [comment]
Great @drselump14 ! I can give you ownership of the `pt` gem as well, what email address do you have associated to your `dr_selump14` user in rubygems.org?

**Comment by drselump14** [comment]
I think it's botoksgonzales@gmail.com

**Comment by raul** [comment]
Excellent, you should be able to manage the repo and the gem now - let me know if you hit any issues. Thanks!

**Comment by drselump14** [comment]
Great, thanks

**Comment by orta** [comment]
Yeah this is awesome! 👍
