### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by graygilmore** [raul/pt#65]
Just installed the gem and tried to setup from within a repo:

```bash
pt started
fatal: Not a git repository (or any of the parent directories): .git
/<LOCAL STUFF>/.gem/ruby/2.2.5/gems/bundler-1.13.6/lib/bundler/resolver.rb:366:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'minitest (~> 5.0)' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
```

Tried a couple of different ruby versions (2.2.5 and 2.3.1) and was unable to start up in either. Is this in a current functioning state? Is there something else I should try?

**Comment by drselump14** [comment]
Ok, I think this is a bug.
But, you can fix it quickly with `gem install minitest`

**Comment by graygilmore** [comment]
That was my first step of action and it unfortunately did not fix anything. If I `gem list` I can see that minitest 5.10.1 is there.

**Comment by drselump14** [comment]
I see. Please wait for a moment, I'll try to fix it asap.

**Comment by drselump14** [comment]
I planned to use minitest as testing for this gem, but I still have no time to write a test code. So, I removed it from dependencies and I'll try to figure it out later.

@graygilmore Please try install the 0.8.4 version, and let me know if it still have problem

**Comment by graygilmore** [comment]
I think it's a larger issue than that. All of those dependencies are being required for some reason.

**Comment by drselump14** [comment]
Yeah, maybe that's the case. I'll figure it out later. Please feel free
to create pull request to fix this problem.

**Comment by drselump14** [comment]
This pull request #66 will fix `fatal: Not a git repository (or any of the parent directories): .git` warning and probably fix the issue about pt complaining about development dependencies not being installed (in this case : minitest gem).

@graygilmore I'll close this issue. Thanks for reporting
