### ISSUE TITLE
Ability to not enter interactive prompt

### ISSUE THREAD

**Issue by shuriu** [raul/pt#70]
I find myself using this gem to see the ids of stories i've started just so I could add the story id to the commit message.

A minor frustration is that after i run `pt started` i need to exit the interactive console using `q > ENTER`. I understand that for browsing this prompt is useful for large lists, but for short ones I'd like to skip the prompt entirely.

Can we add a local config so that the interactive prompt can be skipped or something similar?

**Comment by drselump14** [comment]
hello, thanks for the contribution. I've removed the interactive mode for paging (https://github.com/raul/pt/commit/2dfe8fda3d9c52a661cf3472d4ff6b468dcc3fa3) . Start from version 0.10.0 pagination option can be set using --page and --limit flag.
So, for default using pt with filter method ( started, finished, etc) won't enter interactive prompt. However, for action method (start, finish, estimate, etc), it will enter interactive prompt to select story to execute the action.

regards
